version: '3'
services:
  pyapp:
    build: "./py_app"
    environment:
      - REDIS_PORT=6379
    ports:
      - 5000:5000
  nodeapp:
    build: "./node_app"
    ports:
      - 3000:3000
    volumes:
      - ./node_app:/usr/app
  redis:
    image: redis:alpine
    ports:
       - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    hostname: newrabbit
    ports:
        - 8000:15672
        - 5672:5672
        - 25676:25676
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example